export const get_notHandoverCarList_success = 'get_notHandoverCarList_success'
export const get_notHandoverCarList_failed = 'get_notHandoverCarList_failed'
export const get_notHandoverCarList_error = 'get_notHandoverCarList_error'
export const get_notHandoverCarList_waiting = 'get_notHandoverCarList_waiting'

export const get_notHandoverCarListMore_success = 'get_notHandoverCarListMore_success'
export const get_notHandoverCarListMore_failed = 'get_notHandoverCarListMore_failed'
export const get_notHandoverCarListMore_error = 'get_notHandoverCarListMore_error'
export const get_notHandoverCarListMore_waiting = 'get_notHandoverCarListMore_waiting'